### ISSUE TITLE
How to check current query size to split many bulk insertion queries?

### ISSUE THREAD

**Issue by peter279k** [brick/db#6]
As title, I need to know current query size and I can split current size with bulk insertion builder.

And it will let me avoid getting ` Got a packet bigger than 'max_allowed_packet' bytes` error message.

Is it possible to implement this feature?

**Comment by peter279k** [comment]
My question is very similar with [this](https://stackoverflow.com/questions/37203632/how-to-check-the-current-query-packet-size-for-mysql), but it seems that using `strlen` cannot get current query size to compare to max allowed packet size.

**Comment by BenMorel** [comment]
Hi, it will be hard to implement this feature as I don't think the packet size calculation is easy (the packet is probably bigger than the length of the query and the parameters). I would suggest you calculate the total length of your parameters, multiply this by the number of inserts per query you're planning to use, and take some margin (like half the max packet size) to be on the safe side.

Then adjust the `max_allowed_packet` or the inserts per query accordingly!

**Comment by peter279k** [comment]
Hi @BenMorel, thanks for your reply.

You're right. It's hard to calculate current query size. Even use the `strlen` function to calculate query size in PHP is not correct.

I think the only way is like you suggest.

Using the half length of `max_allowed_packet` size to ensure that every bulk insertion queries will be worked without `Got a packet bigger than 'max_allowed_packet' bytes` message :).
